### ISSUE TITLE
x264 issue with avs reader when using YUV420P10 and some resolutions

### ISSUE THREAD

**Issue by ghost** [Patman86/x264-Mod-by-Patman#1]
Hi @Patman86 

I know that other x264 avs/vpy readers does not support 10bit inputs, but your avs/vpy reader does. However it shows a bug in some conditions. Here is how you can reproduce it:

## Use AviSynth
- load a file in staxrip
- set a resize filter to 856 x 480
- set filter ConvertBits(10)
- Encode using x264 with avs reader (no pipe)

The resulting video appears with a green band on the bottom...

![mpv-shot0001](https://user-images.githubusercontent.com/17828567/110635278-9393d400-81b3-11eb-99e6-0168fafaf610.jpg)

If you encode with avspipe, or remove the resize filter, or remove the convertbits filter, the green band disappears
 

## use Vapoursynth, 

- load a file in staxrip
- set a resize filter to 856 x 480
- set filter clip = core.fmtc.bitdepth(clip, bits=10)
- Encode using x264 with vpy reader (no pipe)

also a green band, but different

![mpv-shot0002](https://user-images.githubusercontent.com/17828567/110635869-43694180-81b4-11eb-9e2b-fad54100f7a8.jpg)

**Comment by Patman86** [comment]
Thanks for reporting the issue.  I'll take a look, it seems to be something general as it occurs with avs and vpy, albeit differently.

**Comment by DJATOM** [comment]
Does it happen with pipe and y4m input?

**Comment by Patman86** [comment]
> Does it happen with pipe and y4m input?

Hi @DJATOM,

that's only happens with direct avs/vpy input. With vspipe y4m or avs2pipemod y4m evrything is okay.

**Comment by DJATOM** [comment]
Yeah, reproduced. Will try to fix, but I don't have an idea what causing it...

**Comment by 44vince44** [comment]
> Does it happen with pipe and y4m input?

nope, only with the readers

**Comment by ghost** [comment]
@DJATOM I tried your compile of x264 but it did not accept 10 bits... (I had a message saying that)

**Comment by DJATOM** [comment]
But it does! Maybe you downloaded some old build where it doesn't had that addition.

**Comment by ghost** [comment]
I downloaded r3039+17-aMod, dated 27 jan 2021...

**Comment by Patman86** [comment]
It's something with the upconvert @DJATOM (avs/vpy contains that)

**Comment by DJATOM** [comment]
Pushed Avisynth fix, will try to use the same approach for Vapoursynth.

**Comment by DJATOM** [comment]
Vapoursynth change is also pushed (but it seems results are nondeterministic, I've got a small bitrate differences - check that carefully).

**Comment by Patman86** [comment]
@DJATOM 
Your changes for vpy cause a green flash screen for me. I saw that you used the `resizer` as base, but this doesn't cause the problem. The problem is caused by the fmtc plugin. Maybe `getPluginByNs` should be used. The arguments would then have to be adapted accordingly.

**Comment by DJATOM** [comment]
@Patman86 code updated.

**Comment by Patman86** [comment]
@DJATOM still green flash screen when the resize and fmtconv plugins are activated. The problem is caused by the fmtconv plugin. If resize is deactivated and only fmtc is activated, you will get a green video as output. It seems to have something to do with 

`const VSFormat* new_format = h->vsapi->registerFormat(vi->format->colorFamily, vi->format->sampleType, 16, vi->format->subSamplingW, vi->format->subSamplingH, core)`

and the part after. I adjusted the code a little to get the avs pendant

```
VSMap* args = h->vsapi->createMap();
const char* error;
VSPlugin* fmtcPlugin = h->vsapi->getPluginById("fmtconv", core);
 
h->vsapi->propSetNode(args, "clip", h->node, paReplace);
h->vsapi->freeNode(h->node);
const VSFormat* new_format = h->vsapi->registerFormat(vi->format->colorFamily, vi->format->sampleType, 16, vi->format->subSamplingW, vi->format->subSamplingH, core);
h->vsapi->propSetInt(args, "csp", new_format->id, paReplace);
VSMap* ret = h->vsapi->invoke(fmtcPlugin, "bitdepth", args);
error = h->vsapi->getError(ret);
if (error)
```

**Comment by ghost** [comment]
seems that vpy is more complicated to fix ?

**Comment by Patman86** [comment]
I haven't really had time to investigate that in the last two days. I'll see that I can take a closer look at it over the weekend.

**Comment by Patman86** [comment]
I've tried a few things now, but I have to deal with Vapoursynth even more intensively. I haven't found a solution yet, I think probably too complicated. Maybe @DJATOM still has an idea.

**Comment by DJATOM** [comment]
I don't have enough time to investigate.

**Comment by Patman86** [comment]
It's not that bad ... I'll look into it a little more. If I still find a solution, I'll let you know.

I could also ask in the doom9 forum

**Comment by ghost** [comment]
Hi @Patman86 @DJATOM I wanted to add (if it still makes some sense, since this whole matter seems forgotten :-(   ):

Regardless of bitdepth, there is also an issue with high fps (like 90fps), with some resolutions...
All color planes seems messed up. I'll put some more info later (screenshot, log)

**Comment by DJATOM** [comment]
I'm planning to go back to old method and fix it, yet I'm busy with work for a while. If you will get a fix if it earlier than me, I'm ok with your implementation.

**Comment by ghost** [comment]
I'm sorry i could not reproduce it. maybe it was still a 10 bit issue. Just made a new encode using 856x480 and made sure it was 8 bit, set 90 fps, and worked correctly.
So I believe the problem was still a 10 bit issue. Sorry for the wrong info.

**Comment by DJATOM** [comment]
Extra conversion only happens for 10-14 bit clips. 8 and 16 bit inputs passed as is.

**Comment by Patman86** [comment]
> Extra conversion only happens for 10-14 bit clips. 8 and 16 bit inputs passed as is.

I agree with you! That's exactly what I found out. I undone the last change locally. So I'm also following your strategy 😉

**Comment by Patman86** [comment]
The same (green band) applies to the pipe mode and the raw format. It's fine with the y4m format.

**Comment by DJATOM** [comment]
Probably we have to memcpy frame data at some conditions, yet I didn't check that.

**Comment by Patman86** [comment]
Will be updated this evening...

**Comment by Patman86** [comment]
I've tested DJATOM's changes / fixes with my build and it seems fine as long as the source file is not an m2ts file. Everything is fine with AVS, but with VPY I get a really strange output. Same result with DJATOM's build.

![image](https://user-images.githubusercontent.com/54327252/117566667-49967400-b0b8-11eb-871c-58cc11a7590f.png)

[Source file](https://file.re/2021/05/13/mo00009/)
[Output file](https://www.privfile.com/download.php?fid=6097a933be211-NzgzNA==)

And with raw format, the problem still exist.

**Comment by DJATOM** [comment]
`vs_bitblt` is at fault here. Fixes posted.

**Comment by ghost** [comment]
@Patman86 Hey how are you... We're still waiting ;-) No pressure 🤣 
But actually, since your x264 has no special optimizations for Staxrip (vs DJATOM's, and please correct me if I'm wrong), we could use @DJATOM 's build. And Staxrip is structurally ready to use that build.
So no rush, and again: no pressure, do the changes whenever you have the time.

**Comment by Patman86** [comment]
Thank you very much for your understanding. I've still tested a little and still looking for a solution for the raw format, since the error still persists there. I'll be upgrading x264 in the next 1-2 days.

**Comment by DJATOM** [comment]
@44vince44 
![Nice meme](https://www.meme-arsenal.com/memes/7fa7de053ba30850441107e96f3bf25e.jpg)

**Comment by DJATOM** [comment]
@Patman86 by raw you meant `--demuxer raw`?

**Comment by DJATOM** [comment]
Perhaps [raw-patch.zip](https://github.com/Patman86/x264-Mod-by-Patman/files/6465799/raw-patch.zip) will work for you? I didn't tested.

**Comment by Patman86** [comment]
Hi DJATOM, yes, I mean the `--demuxer raw`.  I'll test your patch tonight.

**Comment by Patman86** [comment]
Patch had no effect, green glitches all over the screen (avs and vpy)

**Comment by DJATOM** [comment]
But they were gone on my end :D

**Comment by Patman86** [comment]
I correct my feedback, **raw format** in avs and vpy is incorrect (green glitches). Direct processing works wonderfully

**Comment by DJATOM** [comment]
Just tested without my patch and it works fine on my sample and vspipe raw output. 
``` --demuxer raw --fps 24000/1001 --input-depth 10 --input-res 856x480 --input-csp yv12```

**Comment by Patman86** [comment]
Really 🤔
with the settings like [here](https://github.com/Patman86/x264-Mod-by-Patman/issues/1#issuecomment-835758896) glitches, glitches, glitches...
i let it be...

**Comment by DJATOM** [comment]
Source file isn't downloadable, I wanted to try it out...

**Comment by Patman86** [comment]
updated link

**Comment by DJATOM** [comment]
```python3
import vapoursynth as vs
core = vs.core

clip = core.lsmas.LWLibavSource(r'mo00009.m2ts')
clip = core.resize.Point(clip, format=vs.YUV420P10)
clip = core.resize.Bicubic(clip, 856, 480)
clip.set_output()
```
```
vspipe tt.vpy - | C:\Build\x264_aMod_latest\x264.exe --demuxer raw --fps 24000/1001 --input-depth 10 --input-res 856x480 --input-csp i420 -o test.mp4 -
```
It made video without glitches. Idk what actually happens on your side :/

**Comment by Patman86** [comment]
```
import os, sys
import vapoursynth as vs
core = vs.get_core()

sys.path.append(r"H:\Download\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\VS\Scripts")
core.std.LoadPlugin(r"H:\Download\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
core.std.LoadPlugin(r"H:\Download\StaxRip\StaxRip-x64-2.1.8.0-Stable\Apps\Plugins\Dual\L-SMASH-Works\LSMASHSource.dll", altsearchpath=True)
clip = core.lsmas.LWLibavSource(r"D:\x264\_test\Mö00009.m2ts", cachefile=r"D:\x264\_test\Mö00009_temp\temp.lwi")
clip = core.resize.Bicubic(clip, 856, 480)
clip = core.fmtc.bitdepth(clip, bits=10)
clip.set_output()
```

I use the fmtconv plugin for bit depth.
if that really can't be reproduced, I'll stop investing time ^^

**Comment by DJATOM** [comment]
https://file.re/2021/05/13/test/ xD

**Comment by Patman86** [comment]
Really strange
@44vince44 reproducible for you with pipe raw?

**Comment by ghost** [comment]
@Patman86 
I'll try it now !!
But what build do you want me to test? DJATOM's  ?

you also mean that i test pipe: `avs2pipemod raw` and `vspipe raw`, right ?

**Comment by Patman86** [comment]
Pls use DJATOM's build with avs2piepmod and vspipe raw

**Comment by ghost** [comment]
These are the tests I did, the result is OK.



### Test 1:

- 840x488 (this is a 8x8 mod, not 16x16)
- avs2pipemod raw
- demuxer auto (it automatically adds demuxer raw switch)

=> RESULT: NO GLITCHES, ALL OK ✅ 

Log file: [friends47min_new_staxrip.log](https://github.com/Patman86/x264-Mod-by-Patman/files/6473712/friends47min_new_staxrip.log)


![friends47min_new_Thumbnail](https://user-images.githubusercontent.com/17828567/118154729-12112a00-b420-11eb-918d-572669c0c7c4.jpg)



### Test 2:

- 840x488 (this is a 8x8 mod, not 16x16)
- **vspipe raw**
- demuxer automatic

=> RESULT: NO GLITCHES, ALL OK ✅ 

Log file:
[friendsVSraw_staxrip.log](https://github.com/Patman86/x264-Mod-by-Patman/files/6473719/friendsVSraw_staxrip.log)

![friendsVSraw_Thumbnail](https://user-images.githubusercontent.com/17828567/118154748-1b01fb80-b420-11eb-8b62-add8bd375deb.jpg)

Note: did someone say StaxRip thumbnailer is not good ?

**Comment by ghost** [comment]
## NOTE For 10 bit input files in raw mode: the input depth = automatic setting is not convenient, probably because it's RAW!



=> If you don't explicitly set `--input-depth 10`, you get the green glitches all the time like this:

![friendsVSraw 10bits_Thumbnail](https://user-images.githubusercontent.com/17828567/118156369-f3139780-b421-11eb-88bc-5d45c10bb869.jpg)

If you set `--input-depth 10`, then you have a all-ok result:


![friendsVSraw 10bits_Thumbnail neww](https://user-images.githubusercontent.com/17828567/118157504-4f2aeb80-b423-11eb-8d88-15f868fb0dd1.jpg)

**Comment by ghost** [comment]
BUT @DJATOM There is a bug in the VPY reader (x264): 

- x264-aMod-x64-core163-r3059+17 , used the generic optimization build
- load video preferably > 30 minutes, use VaspourSynth
- resize it to 840x488
- convert to bit depth 10
- x264 use automatic input ( = vpy reader), output depth 10

 ENCODE... the encoder will crash after a few minutes of encoding. (the h264 stream will be trimmed)

LOG:
[SAMPLE47minFRIENDS_new_staxrip.log](https://github.com/Patman86/x264-Mod-by-Patman/files/6473959/SAMPLE47minFRIENDS_new_staxrip.log)

**Comment by DJATOM** [comment]
I'm now busy with my new Raspberry Pi4 Model B board, will investigate somehow later.

**Comment by Patman86** [comment]
I hope i (we) fixed everything (except for the raw format)

**Comment by ghost** [comment]
@Patman86 I can confirm the crash does not happen anymore with your latest build (tested with a 47min video)! Thanks 🎉 

Well done !!! 👍🏼 🥇  😁

**Comment by DJATOM** [comment]
So crash happens on `memcpy` call? Weird.

**Comment by ghost** [comment]
@DJATOM well it only happened with the vpy reader, in your build... and it happened after a few minutes of processing....

**Comment by DJATOM** [comment]
And only my build uses frame copies. Okay, I will revert that change.

**Comment by Patman86** [comment]
Seems like that or x264_malloc.
```
pic->img.plane[i] = (uint8_t *)x264_malloc( pic->img.stride[i] * height );
memcpy( pic->img.plane[i], readPtr, pic->img.stride[i] * height );
```
I have removed both and built the function as with avs.
And i have replaced 
`const uint8_t *readPtr = h->vsapi->getReadPtr( pic->opaque, planes[i] );`
by
`pic->img.plane[i] = (uint8_t*)h->vsapi->getReadPtr( pic->opaque, planes[i] );`
This is how it works ^^
